version: '3.8'

services:
  metar-exporter:
    build: .
    image: python-metar-export
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
